# -*- coding: utf-8 -*-
"""brain_stroke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nsqe0IA40sMS2HXPx2la68UIKIpfQ_H6
"""

import streamlit as st
import numpy as np
import joblib

# Load model
model = joblib.load("stroke_model.pkl")

st.title("Stroke Prediction App")

st.write("Enter patient details:")

# Inputs
age = st.number_input("Age", 0, 100)
hypertension = st.selectbox("Hypertension (0 = No, 1 = Yes)", [0,1])
heart_disease = st.selectbox("Heart Disease (0 = No, 1 = Yes)", [0,1])
avg_glucose_level = st.number_input("Glucose Level")
bmi = st.number_input("BMI")

# Predict button
if st.button("Predict"):

    input_data = np.array([[age, hypertension, heart_disease, avg_glucose_level, bmi]])

    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("⚠️ High Risk of Stroke")
    else:
        st.success("✅ Low Risk of Stroke")